services:

  mongodb:
    image: mongo:8
    container_name: tracker-mongodb
    volumes:
      - mongodb_data:/data/db

  tracker-app:
    build: .
    container_name: tracker-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data: